spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5434/aca'
    username: 'postgres'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  error:
    include-message: always
secret: '\7V:lT@4sfsdterU6b~O(_nt5W0lJl@`wE'